sudo: required
dist: trusty
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
services:
- postgresql
env:
  global:
  - CORE_BRANCH=master
  - PHP_COVERAGE=FALSE
  matrix:
  - DB=sqlite
branches:
  only:
  - master
  - "/^stable\\d+(\\.\\d+)?$/"
  - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/
cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/.npm"
  - "$HOME/.cache/bower"
before_install:
- mysql -u root -e "CREATE USER 'travis'@'localhost'"
- mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'localhost';"
- sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.4' ]; then curl -s -o $HOME/.phpenv/versions/5.4/bin/phpunit
  https://phar.phpunit.de/phpunit-4.8.9.phar; fi"
- sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.4' ]; then chmod +x $HOME/.phpenv/versions/5.4/bin/phpunit;
  fi"
- composer self-update
- composer install
- wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
- bash ./before_install.sh twofactor_totp $CORE_BRANCH $DB
- cd ../core
- php occ app:enable twofactor_totp

before_script:
- cd apps/twofactor_totp
- if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini; fi

script:
- find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;
- cd tests
- phpunit --configuration phpunit.xml
- if [[ "$PHP_COVERAGE" = "TRUE" ]]; then wget https://scrutinizer-ci.com/ocular.phar;
  fi
- if [[ "$PHP_COVERAGE" = "TRUE" ]]; then php ocular.phar code-coverage:upload --format=php-clover
  clover.xml; fi

matrix:
  include:
    - php: 7
      env: "DB=pgsql PHP_COVERAGE=TRUE"
    - php: 7
      env: "DB=mysql"

  fast_finish: true
